export const prizesSeason6 = [
  {
    place: "Champion",
    amount: "888,636,000 VND",
    position: 1,
    descs: [
      "100% scholarship of AI Optimization, Business Case, System Thinking, Reverse Thinking, Digital Performance Management",
      "Scholarship of ACCA, CFA, CMA, FPAC, FRM, Business Intelligence, Excel, Power BI",
      "Certificate of recognition and trophies",
      "Gifts and merchandise from sponsors and RBAC Organizers",
      "Technology gadgets",
    ],
    gradient: "from-yellow-200 to-amber-600",
    gradientR: "bg-gradient-to-r from-yellow-200 to-amber-600",
    gradientTL: "bg-gradient-to-tl from-yellow-200 to-amber-600",
    gradientBR: "bg-gradient-to-br from-yellow-200 to-amber-600",
    bgGradient: "from-yellow-200/20 to-amber-600/20",
    glow: "shadow-chart-4/30",
  },
  {
    place: "1st Runner Up",
    amount: "799,433,200 VND",
    position: 2,
    descs: [
      "Scholarship of AI Optimization, Business Case, System Thinking, Reverse Thinking, Digital Performance Management, ACCA, CFA, CMA, FPAC, Business Intelligence, Excel, Power BI",
      "Vouchers from esteemed sponsors",
      "Certificate of recognition and trophies",
      "Gifts and merchandise from sponsors and RBAC Organizers",
      "Technology gadgets",
    ],
    gradient: "from-gray-400 to-slate-600",
    gradientR: "bg-gradient-to-r from-gray-400 to-slate-600",
    gradientTL: "bg-gradient-to-tl from-gray-400 to-slate-600",
    gradientBR: "bg-gradient-to-br from-gray-400 to-slate-600",
    bgGradient: "from-gray-400/20 to-slate-600/20",
    glow: "shadow-slate-500/20",
  },
  {
    place: "2nd Runner Up",
    amount: "737,118,000 VND",
    position: 3,
    descs: [
      "Scholarship of AI Optimization, Business Case, System Thinking, Reverse Thinking, Digital Performance Management, ACCA, CFA, CMA, FPAC, Business Intelligence, Excel, Power BI",
      "Vouchers from esteemed sponsors",
      "Certificate of recognition and trophies",
      "Gifts and merchandise from sponsors and RBAC Organizers",
      "Technology gadgets",
    ],
    gradient: "from-primary-foreground to-orange-700",
    gradientR: "bg-gradient-to-r from-primary-foreground to-orange-700",
    gradientTL: "bg-gradient-to-tl from-primary-foreground to-orange-700",
    gradientBR: "bg-gradient-to-br from-primary-foreground to-orange-700",
    bgGradient: "from-primary-foreground/20 to-orange-700/20",
    glow: "shadow-amber-500/20",
  },
  {
    place: "4TH & 5TH TEAMS",
    amount: "1,265,117,600 VND",
    position: 4,
    descs: [
      "Scholarship of AI Optimization, Business Case, System Thinking, Reverse Thinking, Digital Performance Management, ACCA, CFA, CMA, FPAC, Business Intelligence, Excel, Power BI",
      "Vouchers from esteemed sponsors",
      "Certificate of recognition and trophies",
      "Gifts and merchandise from sponsors and RBAC Organizers",
    ],
    gradient: "from-primary-foreground to-muted",
    gradientR: "bg-gradient-to-r from-primary-foreground to-muted",
    gradientTL: "bg-gradient-to-tl from-primary-foreground to-muted",
    gradientBR: "bg-gradient-to-br from-primary-foreground to-muted",
    bgGradient: "from-primary-foreground/20 to-muted/20",
    glow: "shadow-muted/20",
  },
  {
    place: "Top 6 - Top 15",
    amount: "5,010,792,000 VND",
    extra: "All Teams",
    position: 5,
    descs: [
      "Scholarship of Digital Performance Management, ACCA, CFA, CMA, FPAC, Business Intelligence, Excel",
      "Digital Certificates",
    ],
    gradient: "from-secondary to-pink-300",
    gradientR: "bg-gradient-to-r from-secondary to-pink-300",
    gradientTL: "bg-gradient-to-tl from-secondary to-pink-300",
    gradientBR: "bg-gradient-to-br from-secondary to-pink-300",
    bgGradient: "from-secondary/20 to-pink-300/20",
    glow: "shadow-secondary/20",
  },
  {
    place: "Top 6 - Top 15",
    amount: "419,188,000 VND",
    extra: "All Teams",
    position: 6,
    descs: [
      "Scholarship of Digital Performance Management, Business Intelligence, Excel",
      "Digital Certificates",
    ],
    gradient: "from-secondary to-pink-300",
    gradientR: "bg-gradient-to-r from-secondary to-pink-300",
    gradientTL: "bg-gradient-to-tl from-secondary to-pink-300",
    gradientBR: "bg-gradient-to-br from-secondary to-pink-300",
    bgGradient: "from-secondary/20 to-pink-300/20",
    glow: "shadow-secondary/20",
  },
  {
    place: "PEOPLE CHOICE AWARDS",
    amount: "13,000,000 VND",
    position: 7,
    descs: [
      "Gifts and merchandise from sponsors and RBAC Organizers Digital Certificates",
      "Phu Hung Life: 2 internships with a monthly allowance of 3,000,000 VND and a commitment to work for 2 months",
    ],
    gradient: "from-secondary to-pink-300",
    gradientR: "bg-gradient-to-r from-secondary to-pink-300",
    gradientTL: "bg-gradient-to-tl from-secondary to-pink-300",
    gradientBR: "bg-gradient-to-br from-secondary to-pink-300",
    bgGradient: "from-primary/20 to-pink-300/20",
    glow: "shadow-secondary/20",
  },
  {
    place: "PARTICIPANTS",
    amount: "1,739,850,000 VND",
    position: 8,
    extra: "All Teams Round 1 Submissions",
    descs: [
      "Vouchers for Digital Performance Management, CFA, FRM Digital Certificates",
    ],
    gradient: "from-secondary to-pink-300",
    gradientR: "bg-gradient-to-r from-secondary to-pink-300",
    gradientTL: "bg-gradient-to-tl from-secondary to-pink-300",
    gradientBR: "bg-gradient-to-br from-secondary to-pink-300",
    bgGradient: "from-primary/30 to-pink-300/30",
    glow: "shadow-secondary/20",
  },
];

export const roundSeason6 = [
  {
    id: "open-ceremony",
    title: "OPENING CEREMONY",
    date: "7:00 PM - 9:00 PM, Friday, 10 October 2025",
    format: " [ONLINE] Livestream on RBAC Fanpage and Youtube",
    description:
      "Introduction to RBAC Season 6, competition rules, and Q&A session",
    icon: "🎯",
  },
  {
    id: "round1",
    title: "ROUND 01: PRELIMINARY ROUND",
    date: "11 October 2025",
    format: "[ONLINE] Online test on Base.vn platform",
    description:
      "Each team (4 members) will have 120 minutes to answer 30 questions and a mini case study regarding numerical, logical, etc., from our academic sponsor's industry to analyze, visualize, and give business insights",
    icon: "📊",
  },
  {
    id: "round2",
    title: "ROUND 02: FROM DATA TO INSIGHTS",
    date: "17-22 October 2025",
    format: "[ONLINE] Advanced business case with real-world data",
    description:
      "The top 30 teams will receive a Case Study package. Each team has to create a slide presentation that analyses, visualizes, and provides business insights, and submit it together with your written analysis.",
    icon: "🚀",
  },
  {
    id: "round3",
    title: "FINAL ROUND",
    date: "29 Oct - 5 Nov 2025",
    format: "[ONLINE] Advanced case study analysis",
    description:
      "The top 5 teams will receive an advanced case study package based on Round 2. Each team will utilize the given dataset to create a storyboard to analyze, visualize, and provide business insights.",
    icon: "🏆",
  },
  {
    id: "closing-ceremony",
    title: "GRAND FINALE & CLOSING CEREMONY",
    date: "12 November 2025",
    format: "RMIT University Vietnam Saigon South Campus",
    description:
      "The Top 5 teams will take the stage with their live pitches and answer questions from our Judges. The event will conclude with the announcement of results and awarding of prizes.",
    icon: "🎉",
  },
];
export const rulesSeason6 = [
  {
    title: "Eligibility",
    items: [
      "All nationalities accepted",
      "Undergraduate students in Vietnam",
      "Previous top 5 finalists cannot participate",
    ],
    bgColor: "bg-blue-900/20",
    borderColor: "border-blue-500/20",
    hoverBorderColor: "hover:border-blue-400/30",
    dotColor: "bg-blue-400",
    textColor: "text-blue-400",
  },
  {
    title: "Registration",
    items: [
      "4 members per team",
      "One team per contestant",
      "Cross-university teams allowed",
    ],
    bgColor: "bg-purple-900/20",
    borderColor: "border-purple-500/20",
    hoverBorderColor: "hover:border-purple-400/30",
    dotColor: "bg-purple-400",
    textColor: "text-purple-400",
  },
  {
    title: "Notes",
    items: [
      "Follow all regulations",
      "English sessions & submissions",
      "Organizers can disqualify violations",
    ],
    bgColor: "bg-cyan-900/20",
    borderColor: "border-cyan-500/20",
    hoverBorderColor: "hover:border-cyan-400/30",
    dotColor: "bg-cyan-400",
    textColor: "text-cyan-400",
  },
];

export const sponsorSeason6 = [
  {
    level: "Case Sponsor",
    sponsors: [
      {
        name: "/sponsors/1. CASE sponsor/Colgate-Pamolive.png",
        width: 1600,
        height: 500,
        type: "case",
      },
    ],
    gradient: "from-yellow-300/40 to-amber-500/40",
    borderColor: "border-yellow-500/40",
  },
  {
    level: "Silver Sponsor",
    sponsors: [
      {
        name: "/sponsors/3 SILVER Sponsor/amiCoach.jpg",
        width: 1417,
        height: 320,
        type: "silver",
      },
      {
        name: "/sponsors/3 SILVER Sponsor/MCI.png",
        width: 2063,
        height: 875,
        type: "silver",
      },
      {
        name: "/sponsors/3 SILVER Sponsor/UniTrain.png",
        width: 2309,
        height: 320,
        type: "silver",
      },
      {
        name: "/sponsors/3 SILVER Sponsor/LTPEDTECH.jpg",
        width: 1276,
        height: 1280,
        type: "silver",
      },
    ],
    gradient: "from-gray-400/40 to-slate-600/40",
    borderColor: "border-gray-500/40",
  },
  {
    level: "Bronze Sponsor",
    sponsors: [
      {
        name: "/sponsors/4. BRONZE Sponsor/Student Council.jpeg",
        width: 2048,
        height: 320,
        type: "bronze",
      },
      {
        name: "/sponsors/4. BRONZE Sponsor/Smart Train.jpg",
        width: 2048,
        height: 2048,
        type: "bronze",
      },
    ],
    gradient: "from-amber-700/40 to-amber-900/40",
    borderColor: "border-amber-600/40",
  },
  {
    level: "Academic Sponsor",
    sponsors: [
      {
        name: "/sponsors/5. ACEDEMIC Sponsor/WiDS.jpg",
        width: 6438,
        height: 1750,
        type: "academic",
      },
      {
        name: "/sponsors/5. ACEDEMIC Sponsor/IEP.png",
        width: 1579,
        height: 503,
        type: "academic",
      },
      {
        name: "/sponsors/5. ACEDEMIC Sponsor/Mastering Data Analysis.png",
        width: 2048,
        height: 2048,
        type: "academic",
      },
      {
        name: "/sponsors/5. ACEDEMIC Sponsor/TymeX.jpg",
        width: 900,
        height: 900,
        type: "academic",
      },
      {
        name: "/sponsors/5. ACEDEMIC Sponsor/TechCamp.jpg",
        width: 900,
        height: 900,
        type: "academic",
      },
    ],
    gradient: "from-blue-400/40 to-blue-700/40",
    borderColor: "border-blue-500/40",
  },
  {
    level: "Scholarship Sponsor",
    sponsors: [
      {
        name: "/sponsors/6. SCHOLARSHIP Sponsor/Tomorrow Marketers.jpg",
        width: 898,
        height: 300,
        type: "scholarship",
      },
      {
        name: "/sponsors/6. SCHOLARSHIP Sponsor/VTI Academy  .jpg",
        width: 1024,
        height: 1024,
        type: "scholarship",
      },
      {
        name: "/sponsors/6. SCHOLARSHIP Sponsor/PMAX Academy.jpg",
        width: 1024,
        height: 1024,
        type: "scholarship",
      },
      {
        name: "/sponsors/6. SCHOLARSHIP Sponsor/SAPP logo mới-01.png",
        width: 1024,
        height: 320,
        type: "scholarship",
      },
    ],
    gradient: "from-green-400/40 to-green-700/40",
    borderColor: "border-green-500/40",
  },
  {
    level: "Platform Sponsor",
    sponsors: [
      {
        name: "/sponsors/7. PLATFORM Sponsor/Tuturuuu Dark.png",
        width: 2554,
        height: 340,
        type: "platform",
      },
      {
        name: "/sponsors/7. PLATFORM Sponsor/TuongTac.TV.png",
        width: 2554,
        height: 606,
        type: "platform",
      },
      {
        name: "/sponsors/7. PLATFORM Sponsor/Base VN.jpeg",
        width: 772,
        height: 320,
        type: "platform",
      },
    ],
    gradient: "from-purple-400/40 to-purple-700/40",
    borderColor: "border-purple-500/40",
  },
  {
    level: "Companion Sponsor",
    sponsors: [
      {
        name: "/sponsors/8. COMPANION Sponsor/Jósie Flowers.jpg",
        width: 2560,
        height: 2560,
        type: "companion",
      },
      {
        name: "/sponsors/8. COMPANION Sponsor/PT.png",
        width: 885,
        height: 699,
        type: "companion",
      },
      {
        name: "/sponsors/8. COMPANION Sponsor/CANIFA.png",
        width: 2048,
        height: 2048,
        type: "companion",
      },
      {
        name: "/sponsors/8. COMPANION Sponsor/Logitech_logo.png",
        width: 431,
        height: 136,
        type: "companion",
      },
    ],
    gradient: "from-pink-400/40 to-pink-700/40",
    borderColor: "border-pink-500/40",
  },
  {
    level: "Reward Sponsor",
    sponsors: [
      {
        name: "/sponsors/9. REWARD Sponsor/Bitis Hunter .png",
        width: 1780,
        height: 358,
        type: "reward",
      },
      {
        name: "/sponsors/9. REWARD Sponsor/Phú Hưng Life (VIET).png",
        width: 1790,
        height: 320,
        type: "reward",
      },
      {
        name: "/sponsors/9. REWARD Sponsor/Cake.jpg",
        width: 1200,
        height: 1200,
        type: "reward",
      },
    ],
    gradient: "from-red-400/40 to-red-700/40",
    borderColor: "border-red-500/40",
  },
  {
    level: "F&B Sponsor",
    sponsors: [
      {
        name: "/sponsors/10. F&B Sponsor/FARO INSPIRATION.png",
        width: 4500,
        height: 4500,
        type: "f&b",
      },
      {
        name: "/sponsors/10. F&B Sponsor/FARO ROASTERY.png",
        width: 1080,
        height: 1080,
        type: "f&b",
      },
      {
        name: "/sponsors/10. F&B Sponsor/Samy Street.png",
        width: 2802,
        height: 1506,
        type: "f&b",
      },
    ],
    gradient: "from-orange-400/40 to-orange-700/40",
    borderColor: "border-orange-500/40",
  },
];
