export const seasonList = [
  {
    topic: "Retail",
    logo: "ss1-logo.png",
    partners: [
      { name: "FTMS.jpg", width: 960, height: 195 },
      { name: "KPMG.jpg", width: 2048, height: 776 },
      { name: "Lasluz.png", width: 700, height: 400 },
      { name: "mazars.jpg", width: 2048, height: 724 },
    ],
    highlightJoiner: [
      {
        name: "ss1-winner.jpg",
        width: 1169,
        height: 783,
      },
      {
        name: "ss1-highlight-1.jpg",
        width: 1169,
        height: 783,
      },
      {
        name: "ss1-highlight-2.jpg",
        width: 1176,
        height: 783,
      },
      {
        name: "ss1-highlight-4.jpg",
        width: 1176,
        height: 783,
      },
      {
        name: "ss1-highlight-5.jpg",
        width: 1176,
        height: 783,
      },
    ],
  },
  {
    topic: "Finance and Logistics in FMCG companies",
    partners: [
      { name: "BAC.png", width: 405, height: 259 },
      { name: "Deloitte.jpg", width: 1612, height: 845 },
      { name: "MasteringData.png", width: 2048, height: 2048 },
      { name: "Nordic.png", width: 700, height: 400 },
      { name: "Pepsi.jpg", width: 960, height: 959 },
      { name: "Prudential.png", width: 348, height: 196 },
      { name: "RMIT.png", width: 943, height: 295 },
      { name: "SAPP.png", width: 408, height: 220 },
      { name: "StudentCouncil.jpeg", width: 2048, height: 1121 },
      { name: "UNITRAIN.png", width: 4416, height: 2543 },
    ],
    logo: "ss2-logo.png",
    highlightJoiner: [
      { name: "ss2-winner.png", width: 1080, height: 1080 },
      { name: "ss2-highlight-1.png", width: 1080, height: 1080 },
      { name: "ss2-highlight-2.png", width: 1080, height: 1080 },
      { name: "ss2-highlight-4.png", width: 1080, height: 1080 },
      { name: "ss2-highlight-5.png", width: 1080, height: 1080 },
    ],
  },
  {
    topic: "Recommerce",
    partners: [
      { name: "MasteringData.png", width: 2048, height: 2048 },
      { name: "StudentCouncil.jpeg", width: 2048, height: 1121 },
      { name: "UNITRAIN.png", width: 4416, height: 2543 },
      { name: "RMIT.png", width: 943, height: 295 },
      { name: "Ipsos.png", width: 1200, height: 1106 },
      { name: "Smarttrain.jpg", width: 2048, height: 2048 },
      { name: "BAC.png", width: 405, height: 259 },
      { name: "GrantThornton.jpeg", width: 1627, height: 595 },
      { name: "chotot.png", width: 900, height: 900 },
      { name: "Kpim.png", width: 765, height: 768 },
    ],
    logo: "ss3-logo.png",
    highlightJoiner: [
      { name: "ss3-winner.png", width: 2048, height: 2048 },
      { name: "ss3-highlight-1.png", width: 2048, height: 2048 },
      { name: "ss3-highlight-2.png", width: 2048, height: 2048 },
      { name: "ss3-highlight-4.png", width: 2048, height: 2048 },
      { name: "ss3-highlight-5.png", width: 2048, height: 2048 },
    ],
  },
  {
    topic: "Food and Beverage Service",
    partners: [
      { name: "MasteringData.png", width: 2048, height: 2048 },
      { name: "StudentCouncil.jpeg", width: 2048, height: 1121 },
      { name: "UNITRAIN.png", width: 4416, height: 2543 },
      { name: "RMIT.png", width: 943, height: 295 },
      { name: "Ipsos.png", width: 1200, height: 1106 },
      { name: "Smarttrain.jpg", width: 2048, height: 2048 },
      { name: "SAPP.png", width: 408, height: 220 },

      { name: "homecredit.png", width: 2560, height: 1088 },
      { name: "pizzahut.png", width: 2176, height: 2049 },
      { name: "basevn.jpeg", width: 772, height: 240 },
      { name: "Quickom.png", width: 1217, height: 383 },
      { name: "TM.jpg", width: 6480, height: 1488 },
      { name: "Gitiho.png", width: 2401, height: 801 },
      { name: "DataStation.png", width: 1500, height: 403 },
    ],
    logo: "ss4-logo.png",
    highlightJoiner: [
      { name: "ss4-winner.png", width: 2000, height: 2000 },
      { name: "ss4-highlight-1.png", width: 2000, height: 2000 },
      { name: "ss4-highlight-2.png", width: 2000, height: 2000 },
      { name: "ss4-highlight-4.png", width: 2000, height: 2000 },
      { name: "ss4-highlight-5.png", width: 2000, height: 2000 },
    ],
  },
  {
    topic: "Finance",
    // partners: [
    //   "PVM.png",
    //   "AME.jpg",
    //   "Cali-OriginalLogo-Red.png",
    //   "chinsu-b7f.png",
    //   "chinsu.png",
    //   "ede.jpg",
    //   "enviet.png",
    //   "Fide.png",
    //   "gft.jpg",
    //   "Kmin.png",
    //   "Lapetal.png",
    //   "Letgreen.jpg",
    //   "logo_XuanThu_ngang.png",
    //   "masan.png",
    //   "Mastering Data.png",
    //   "NUTRIBOOST LOGO-01.png",
    //   "Omachi.png",
    //   "pmax.png",
    //   "Puffme.jpg",
    //   "qhome.png",
    //   "Rebirth-candle.jpg",
    //   "SAPP.png",
    //   "SHBFC.png",
    //   "Shopee.png",
    //   "Silis.jpg",
    //   "Smarttrain.jpg",
    //   "Step-Vietnam-Frame-Red-Logo.png",
    //   "StudentCouncil.jpeg",
    //   "TECHFILM.jpg",
    //   "TM.jpg",
    //   "Yahon.jpg",
    // ],
    partners: [
      {
        name: "all-logo.png",
        width: 2344,
        height: 190,
      },
    ],
    logo: "ss5-logo.png",
    judges: [
      {
        name: "NGUYEN TRUONG GIANG",
        position: "Senior Modeler in Risk Management Division at SHBFinance",
        image: "ss5_mr_giang.png",
      },
      {
        name: "BUI HOANG MY LINH",
        position: "Head of Financial Planning and Business Partner at AIA",
        image: "ss5_linh_bui.png",
      },
      {
        name: "PHAM MINH QUANG",
        position: "Founder & CEO Tomorrow Marketers - TM Data School",
        image: "ss5_mr_quang.png",
      },
      {
        name: "TRAN THI MINH HA",
        position: "RGM and Analytics Director at Coca-Cola Vietnam",
        image: "ss5_ms_ha.png",
      },
      {
        name: "KHOI TRAN",
        position: "Senior Business Analyst at GFT Technologies Vietnam",
        image: "ss5_mr_khoi.png",
      },
      {
        name: "BRIAN LE",
        position: "Senior Scrum Master at GFT Technologies Vietnam",
        image: "ss5_brain_le.png",
      },
      {
        name: "NGUYEN LAM",
        position: "Staffing Manager at GFT Technologies Vietnam",
        image: "ss5_ng_lam.png",
      },
      {
        name: "TAM TRUONG",
        position: "Data Service & Management Manager at ACFC",
        image: "ss5_tam_truong.png",
      },
      {
        name: "DUC LE",
        position:
          "Head of Business Intelligence and Data Analysis at Ngân hàng số Cake by VPBank",
        image: "ss5_duc_le.png",
      },
      {
        name: "LINH NGUYEN",
        position: "Head of Data Analytics at Xanh SM",
        image: "ss5_linh_nguyen.png",
      },
    ],
    mentors: [
      {
        name: "VIET LO",
        position: "Financial Planning and Analyst at Nestle",
        image: "ss5_viet_lo.png",
      },
      {
        name: "TUAN MAI",
        position: "Data Engineer at Orient Commercial Joint Stock Bank (OCB)",
        image: "ss5_tuan_mai.png",
      },
      {
        name: "DUC LE",
        position:
          "Head of Business Intelligence and Data Analysis at Ngân hàng số Cake by VPBank",
        image: "ss5_duc_le.png",
      },
      {
        name: "NHAN BUI",
        position: "Data Analytics Team Leader at Toshiba Logistics Vietnam",
        image: "ss5_nhan_bui.png",
      },
      {
        name: "HUNG TRAN",
        position: "Business Intelligence Director at Techcombank",
        image: "ss5_hung_tran.png",
      },
    ],
    highlightJoiner: [
      { name: "ss5-winner.png", width: 2563, height: 1625 },
      { name: "ss5-highlight-1.png", width: 2563, height: 1625 },
      { name: "ss5-highlight-2.png", width: 2563, height: 1625 },
      { name: "ss5-highlight-4.png", width: 2563, height: 1625 },
      { name: "ss5-highlight-5.png", width: 2563, height: 1625 },
    ],
  },
];
